### ISSUE TITLE
Flatpak does not start

### ISSUE THREAD

**Issue by hz61p1** [bitwarden/desktop#1034]
## Describe the Bug

Does not start

## Steps To Reproduce

1. Open terminal
2. ```flatpak run com.bitwarden.desktop```

## Expected Result

Launching the program

## Actual Result

```
➜  ~ flatpak run com.bitwarden.desktop
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/Bitwarden/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
Gtk-Message: 14:25:04.578: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:25:04.578: Failed to load module "pk-gtk-module"
Gtk-Message: 14:25:04.578: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:25:04.578: Failed to load module "pk-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
```

## Screenshots or Videos

Not needed

## Environment

- Operating system: Fedora 34 Workstation with the latest updates
- Installation method: Flatpak with Flathub

## Additional Context

```
➜  ~ flatpak info com.bitwarden.desktop

Bitwarden - A secure and free password manager for all of your devices

          ID: com.bitwarden.desktop
         Ref: app/com.bitwarden.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.28.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 207.4 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 3f95d1c29957a4d3f4fe4f5c95fd4caceb895fe57c1d6cbcc2772e1be54b824a
      Parent: 30548d5bc3b36d461714f993f6af05c6b86acb5d91259b240d606cb8bb41d22d
     Subject: Update Bitwarden-1.27.1-amd64.deb to 1.28.0 (837b9ad4)
        Date: 2021-08-19 21:27:48 +0000

```

**Comment by Hinton** [comment]
Bitwarden does not currently maintain an official flatpack package. https://flathub.org/apps/details/com.bitwarden.desktop seems to point to https://github.com/flathub/com.bitwarden.desktop

**Comment by martywd** [comment]
fwiw, I've created an issue over at ==> https://github.com/flathub/com.bitwarden.desktop/issues/75

.
