### ISSUE TITLE
Minimize to tray error on Windows 10

### ISSUE THREAD

**Issue by keeneye** [bitwarden/desktop#111]
I can't get the miminise to tray to work at all on Windows 10 (1803). I get this Javascript error.
![image](https://user-images.githubusercontent.com/1785742/43065267-3ce19a98-8e59-11e8-970d-f770429b073c.png).
Sometime the icon appears in the tray but doesn't do anything. Then the Windows app doesn't work at all.
Mark

**Comment by kspearrin** [comment]
Is this installed through Windows Store? Does it work if you install outside of the store?

**Comment by twittwer** [comment]
I get the same error on macOS 10.13.6
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TrayMain.showTray (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:1839:19)
    at TrayMain.hideToTray (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:1829:14)
    at MessagingMain.onMessage (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:1130:36)
    at ElectronMainMessagingService.Main.messagingService.__WEBPACK_IMPORTED_MODULE_10_jslib_electron_services_electronMainMessaging_service__.a [as onMessage] (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:257:32)
    at ElectronMainMessagingService.send (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:1733:14)
    at click (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:845:53)
    at MenuItem.click (/Applications/Bitwarden.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Applications/Bitwarden.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)
```

**Comment by keeneye** [comment]
Yes - it was the Store version that had the problem on Windows. I've installed outside the Store and it working fine. Thanks for you suggestion.

**Comment by Gary92** [comment]
I confirm that the error occurred in Windows Store version only. With the current release I don't get the error anymore but the tray icon remains useless, as it's not clickable (nothing happens when clicked). Example, if I minimize Bitwarden to the system tray, there's no easy way to restore it. I'm talking about the Windows Store version, of course (that is the version I'd like to use).
