### ISSUE TITLE
v1.29.1 Uncaught Exception - app won't start at all

### ISSUE THREAD

**Issue by edmundlaugasson** [bitwarden/desktop#1143]
### Steps To Reproduce

1. Bitwarden installed [from here](https://archlinux.org/packages/community/x86_64/bitwarden/)
2. trying to run it
3. bunch of error messages and won't run

### Expected Result

App will run normally

### Actual Result

App won't run and gives bunch of errors:
```
App threw an error during load
SyntaxError: Unexpected token � in JSON at position 409908
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/usr/lib/bitwarden/app.asar/node_modules/conf/dist/source/index.js:67:43)
    at ElectronStore.get store [as store] (/usr/lib/bitwarden/app.asar/node_modules/conf/dist/source/index.js:277:43)
    at new Conf (/usr/lib/bitwarden/app.asar/node_modules/conf/dist/source/index.js:130:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/node_modules/electron-store/index.js:69:3)
    at new electronStorage_service_ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:1931:22)
    at new main_Main (/usr/lib/bitwarden/app.asar/main.js:2843:31)
    at Module.<anonymous> (/usr/lib/bitwarden/app.asar/main.js:3109:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:20:30)
    at /usr/lib/bitwarden/app.asar/main.js:84:18
(node:6491) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron --trace-deprecation ...` to show where the warning was created)
```

### Operating System

Linux

### Operating System Version

Linux 5.14.16

### Installation method

Other

### Build Version

9c1aa3f

**Comment by MarcelSchwedtmann** [comment]
Getting error after trying to install flatpak from flathub or popOS Store. Running popOS 21.04
`Aborted due to failure (Während des Versuchs, eine Arbeitskopie von b62fdadf705ad1cc820ff598eb9315d25b4d9eea009b2ca951f1d7696530037c nach /home/USERNAME/.local/share/flatpak/app/com.bitwarden.desktop/x86_64/stable/.b62fdadf705ad1cc820ff598eb9315d25b4d9eea009b2ca951f1d7696530037c-3B0XC1 zu erstellen: Opening content object 28d4643da1b662603b8e8d005e1013fd92bda71bf63f5f0d99d24fa4dd5dd219: Couldn't find file object '28d4643da1b662603b8e8d005e1013fd92bda71bf63f5f0d99d24fa4dd5dd219')`

**Comment by Hinton** [comment]
We are unfortunately not able to provide official support for non-official builds or distributions of Bitwarden.

I'm not familiar with any of the error messages and I suspect it's related to the particular distribution method. Should any of the errors be reproduce-able using an official build from https://bitwarden.com, please feel free to either re-open this issue or create a new one with steps to reproduce.

Thanks.
