### ISSUE TITLE
Application frozen on startup

### ISSUE THREAD

**Issue by pplu** [bitwarden/desktop#1205]
### Steps To Reproduce

1. Set Bitwarden to automatically start up on login
2. Log in to system

### Expected Result

Bitwarden application starts

### Actual Result

Bitwarden application appears on screen, but no menu and no contents

![Screenshot from 2021-12-21 09-50-42](https://user-images.githubusercontent.com/53034/146900865-d10b40cb-b0ac-4cf7-82f7-a88ea443b1d6.png)

The application is irresponsive (cannot close). I have to kill it with `kill PID_OF_BITWARDEN`. After that, if I start the application from the launcher, it works.

In `/var/log/messages' I get:
```
Dec 20 09:34:16 malfunctioning-eddie bitwarden.desktop[3312]: (node:3312) DeprecationWarning: file property is deprecated and will be removed in v5.
Dec 20 09:34:16 malfunctioning-eddie bitwarden.desktop[3312]: (Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Dec 20 09:34:16 malfunctioning-eddie bitwarden.desktop[3312]: [3504:1220/093416.827245:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Dec 20 09:34:17 malfunctioning-eddie bitwarden.desktop[3312]: (node:3312) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
Dec 20 09:34:19 malfunctioning-eddie bitwarden.desktop[3312]: [3312:1220/093419.010831:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]: [3312:1220/094353.524287:ERROR:zygote_communication_linux.cc(276)] Failed to send GetTerminationStatus message to zygote
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]: [3312:1220/094353.525385:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]: [3312:1220/094353.526786:ERROR:gpu_process_host.cc(956)] GPU process launch failed: error_code=1002
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]: 09:43:53.527 › TypeError: Object has been destroyed
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at window_main_WindowMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:2491:36)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at Generator.next (<anonymous>)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at /opt/Bitwarden/resources/app.asar/main.js:2304:71
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at new Promise (<anonymous>)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at window_main_awaiter (/opt/Bitwarden/resources/app.asar/main.js:2300:12)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at window_main_WindowMain.updateWindowState (/opt/Bitwarden/resources/app.asar/main.js:2486:16)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at window_main_WindowMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:2440:28)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at Generator.next (<anonymous>)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at /opt/Bitwarden/resources/app.asar/main.js:2304:71
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]:     at new Promise (<anonymous>)
Dec 20 09:43:53 malfunctioning-eddie bitwarden.desktop[3312]: [3312:1220/094353.534907:ERROR:gpu_process_host.cc(956)] GPU process launch failed: error_code=1002
Dec 20 09:43:57 malfunctioning-eddie bitwarden.desktop[3092]: (node:6167) DeprecationWarning: file property is deprecated and will be removed in v5.
Dec 20 09:43:57 malfunctioning-eddie bitwarden.desktop[3092]: (Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Dec 20 09:43:57 malfunctioning-eddie bitwarden.desktop[3092]: [6200:1220/094357.728280:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Dec 20 09:43:57 malfunctioning-eddie bitwarden.desktop[3092]: (node:6167) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
Dec 20 09:43:58 malfunctioning-eddie bitwarden.desktop[3092]: [6167:1220/094358.565622:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
Dec 20 22:47:21 malfunctioning-eddie bitwarden.desktop[3092]: [6200:1220/224721.887381:ERROR:connection.cc(66)] X connection error received.
Dec 20 22:47:21 malfunctioning-eddie bitwarden.desktop[3092]: [6200:1220/224721.887343:ERROR:connection.cc(66)] X connection error received.
Dec 20 22:47:22 malfunctioning-eddie bitwarden[6167]: bitwarden: Fatal IO error 0 (Success) on X server :0.
Dec 21 09:42:02 malfunctioning-eddie bitwarden.desktop[1968]: (node:1968) DeprecationWarning: file property is deprecated and will be removed in v5.
Dec 21 09:42:02 malfunctioning-eddie bitwarden.desktop[1968]: (Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Dec 21 09:42:03 malfunctioning-eddie bitwarden.desktop[1968]: [2154:1221/094203.111328:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Dec 21 09:42:03 malfunctioning-eddie bitwarden.desktop[1968]: (node:1968) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
Dec 21 09:42:05 malfunctioning-eddie bitwarden.desktop[1968]: [1968:1221/094205.174752:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
```

### Additional Context

My settings for application startup are:

- [x] Enable Tray Icon
- [x] Close to Tray Icon
- [x] Start to Tray Icon
- [x] Start automatically on login

### Operating System

Linux

### Operating System Version

Debian 10.11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.30.0 Shell 14.2.0 Renderer 93.0.4577.82 Node 14.17.0 Architecture x64

**Comment by pplu** [comment]
More info: it's the "Start to Tray Icon" that is causing the UI to not load. If I deactivate the "Start to Tray Icon" option, Bitwarden will display on session startup.

**Comment by gcortanato** [comment]
Same issue on Windows 11
