### ISSUE TITLE
Help with launcher script for flatpak

### ISSUE THREAD

**Issue by ghisvail** [bitwarden/desktop#126]
I am in the process of submitting a [flatpak](https://github.com/flathub/flathub/pull/547) for the Bitwarden desktop application.

It builds fine and in a reproducible fashion on x86 architectures, which is a good start. I filed a separate [issue for ARM builds](https://github.com/bitwarden/desktop/issues/125).

However, I am struggling with the definition of an appropriate launcher script for the flatpak entrypoint (basically triggered with `flatpak run com.bitwarden.desktop`). For Electron apps I have packaged previously, the script is as simple as running `npm start --prefix=/app/main`, whereby `/app/main` is where the output of `npm install` is moved inside the flatpak sandbox. Here is an example for [draw.io](https://github.com/flathub/com.jgraph.drawio.desktop/blob/a310451027fb8d0f2536cc19265b43393bfa9b45/com.jgraph.drawio.desktop.yml#L56).

Could you help me define such wrapper script for Bitwarden, please?

**Comment by kspearrin** [comment]
I added a new `start` script that should help.

Process to run should look like:

```
npm run build
npm start
```

**Comment by ghisvail** [comment]
Thanks for looking into it. I have got a few questions:

- Since the flatpak packaging process dissociates the build stage and run stage, I guess I'll have to put `npm install` and `npm run build` in the build commands, and `npm start` in the launcher script. Could you confirm?

- Will your `npm run build` and `npm start` scripts honor the `--prefix` option?

**Comment by ghisvail** [comment]
`--prefix` avoids having to prefix and suffix `npm` calls with `cd` commands.

**Comment by ghisvail** [comment]
I get the following outcome:
```
Running: npm run build --prefix=main --offline --cache=/run/build/bitwarden/npm-cache --nodedir=/app
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.11.3
npm info lifecycle bitwarden@0.0.0~prebuild: bitwarden@0.0.0
npm info lifecycle bitwarden@0.0.0~build: bitwarden@0.0.0

> bitwarden@0.0.0 build /run/build/bitwarden/main
> concurrently -n Main,Rend -c yellow,cyan "npm run build:main" "npm run build:renderer"

[Rend] npmnpm info it worked if it ends with ok
[Main] npm info using npm@5.6.0
[Main] npm info using node@v8.11.3
[Rend]  info it worked if it ends with ok
[Rend] npm info using npm@5.6.0
[Rend] npm info using node@v8.11.3
[Main] npm info lifecycle bitwarden@0.0.0~prebuild:main: bitwarden@0.0.0
[Main] npm info lifecycle bitwarden@0.0.0~build:main: bitwarden@0.0.0
[Rend] npm info lifecycle bitwarden@0.0.0~prebuild:renderer: bitwarden@0.0.0
[Rend] npm info lifecycle bitwarden@0.0.0~build:renderer: bitwarden@0.0.0
[Main] 
[Main] > bitwarden@0.0.0 build:main /run/build/bitwarden/main
[Main] > webpack --config webpack.main.js
[Main] 
[Rend] 
[Rend] > bitwarden@0.0.0 build:renderer /run/build/bitwarden/main
[Rend] > gulp prebuild:renderer && webpack --config webpack.renderer.js
[Rend] 
[Rend] [13:45:02] Using gulpfile /run/build/bitwarden/main/gulpfile.js
[Rend] [13:45:02] Starting 'clean'...
[Rend] [13:45:02] Finished 'clean' after 23 ms
[Rend] [13:45:02] Starting 'webfonts'...
[Rend] events.js:183
[Rend]       throw er; // Unhandled 'error' event
[Rend]       ^
[Rend] 
[Rend] Error: getaddrinfo ENOTFOUND fonts.googleapis.com fonts.googleapis.com:443
[Rend]     at errnoException (dns.js:50:10)
[Rend]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
[Rend] npm info lifecycle bitwarden@0.0.0~build:renderer: Failed to exec build:renderer script
[Rend] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[Rend] npm ERR! bitwarden@0.0.0 build:renderer: `gulp prebuild:renderer && webpack --config webpack.renderer.js`
[Rend] npm ERR! Exit status 1
[Rend] npm ERR! 
npm ERR! Failed at the bitwarden@0.0.0 build:renderer script.
[Rend] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[Rend] 
[Rend] npm ERR! A complete log of this run can be found in:
[Rend] npm ERR!     /run/build/bitwarden/npm-cache/_logs/2018-08-27T11_45_02_444Z-debug.log
[Rend] npm run build:renderer exited with code 1
[Main] clean-webpack-plugin: /run/build/bitwarden/main/build/* has been removed.
[Main] Hash: 816f43ec2d51e66e9199
[Main] Version: webpack 3.12.0
[Main] Time: 10723ms
[Main]                        Asset       Size  Chunks             Chunk Names
[Main]     locales/es/messages.json    26.9 kB          [emitted]  
[Main]                      main.js     101 kB       0  [emitted]  main
[Main]          images/fa-globe.png  344 bytes          [emitted]  
[Main]    images/icon-highlight.png  292 bytes          [emitted]  
[Main] images/icon-highlight@2x.png  438 bytes          [emitted]  
[Main]     images/icon-template.png  292 bytes          [emitted]  
[Main]  images/icon-template@2x.png  438 bytes          [emitted]  
[Main]              images/icon.ico    20.2 kB          [emitted]  
[Main]              images/icon.png    12.3 kB          [emitted]  
[Main]           images/loading.svg  291 bytes          [emitted]  
[Main]      images/logo-dark@2x.png    9.32 kB          [emitted]  
[Main]     images/logo-white@2x.png    9.25 kB          [emitted]  
[Main]      images/two-factor/0.png    6.05 kB          [emitted]  
[Main]      images/two-factor/1.png    2.67 kB          [emitted]  
[Main]      images/two-factor/2.png    1.21 kB          [emitted]  
[Main]      images/two-factor/3.png    1.62 kB          [emitted]  
[Main]      images/two-factor/4.png    4.81 kB          [emitted]  
[Main]      images/two-factor/6.png    1.21 kB          [emitted]  
[Main]           images/yubikey.jpg    28.2 kB          [emitted]  
[Main]     locales/bg/messages.json    30.4 kB          [emitted]  
[Main]            images/u2fkey.jpg     178 kB          [emitted]  
[Main]     locales/cs/messages.json    26.7 kB          [emitted]  
[Main]     locales/da/messages.json    25.6 kB          [emitted]  
[Main]     locales/en/messages.json    25.1 kB          [emitted]  
[Main]     locales/de/messages.json    26.7 kB          [emitted]  
[Main]                 package.json  575 bytes          [emitted]  
[Main]     locales/et/messages.json    25.7 kB          [emitted]  
[Main]     locales/fa/messages.json    31.4 kB          [emitted]  
[Main]     locales/fi/messages.json      26 kB          [emitted]  
[Main]     locales/fr/messages.json    27.9 kB          [emitted]  
[Main]     locales/hr/messages.json    26.4 kB          [emitted]  
[Main]     locales/hu/messages.json      27 kB          [emitted]  
[Main]     locales/id/messages.json    25.5 kB          [emitted]  
[Main]     locales/it/messages.json    26.6 kB          [emitted]  
[Main]     locales/ja/messages.json    28.4 kB          [emitted]  
[Main]     locales/ko/messages.json    27.2 kB          [emitted]  
[Main]     locales/nb/messages.json    26.2 kB          [emitted]  
[Main]     locales/nl/messages.json    26.3 kB          [emitted]  
[Main]     locales/pl/messages.json    26.8 kB          [emitted]  
[Main]  locales/pt_BR/messages.json    26.6 kB          [emitted]  
[Main]  locales/pt_PT/messages.json    26.9 kB          [emitted]  
[Main]     locales/ro/messages.json    26.9 kB          [emitted]  
[Main]     locales/ru/messages.json    32.8 kB          [emitted]  
[Main]     locales/sk/messages.json    26.6 kB          [emitted]  
[Main]     locales/sv/messages.json    25.8 kB          [emitted]  
[Main]     locales/th/messages.json    29.8 kB          [emitted]  
[Main]     locales/tr/messages.json    26.6 kB          [emitted]  
[Main]     locales/uk/messages.json    33.2 kB          [emitted]  
[Main]     locales/vi/messages.json    28.5 kB          [emitted]  
[Main]  locales/zh_CN/messages.json    24.5 kB          [emitted]  
[Main]  locales/zh_TW/messages.json    24.5 kB          [emitted]  
[Main]    [4] ./jslib/src/services/constants.service.ts 1.79 kB {0} [built]
[Main]    [7] ./src/main.ts 4.71 kB {0} [built]
[Main]    [8] ./src/services/i18n.service.ts 940 bytes {0} [built]
[Main]   [10] ./src/main/menu.main.ts 20.1 kB {0} [built]
[Main]   [12] ./src/main/messaging.main.ts 2.55 kB {0} [built]
[Main]   [13] ./src/main/powerMonitor.main.ts 2.31 kB {0} [built]
[Main]   [15] ./jslib/src/services/lowdbStorage.service.ts 1.48 kB {0} [built]
[Main]   [18] ./jslib/src/misc/nodeUtils.ts 613 bytes {0} [built]
[Main]   [19] ./jslib/src/misc/utils.ts 9.29 kB {0} [built]
[Main]   [20] ./jslib/src/electron/keytarStorageListener.ts 1.73 kB {0} [built]
[Main]   [22] ./jslib/src/electron/services/electronLog.service.ts 1.44 kB {0} [built]
[Main]   [24] ./jslib/src/electron/services/electronMainMessaging.service.ts 444 bytes {0} [built]
[Main]   [25] ./jslib/src/electron/tray.main.ts 4.46 kB {0} [built]
[Main]   [27] ./jslib/src/electron/updater.main.ts 6.23 kB {0} [built]
[Main]   [29] ./jslib/src/electron/window.main.ts 9.62 kB {0} [built]
[Main]     + 16 hidden modules
[Main] npm info lifecycle bitwarden@0.0.0~postbuild:main: bitwarden@0.0.0
[Main] npm info ok 
[Main] npm run build:main exited with code 0
npm info lifecycle bitwarden@0.0.0~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden@0.0.0 build: `concurrently -n Main,Rend -c yellow,cyan "npm run build:main" "npm run build:renderer"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitwarden@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/bitwarden/npm-cache/_logs/2018-08-27T11_45_13_387Z-debug.log
```

**Comment by kspearrin** [comment]
Looks like your build failed because it could not download the webfonts for whatever reason:

```
getaddrinfo ENOTFOUND fonts.googleapis.com fonts.googleapis.com:443
```

Do you have internet connection?

**Comment by ghisvail** [comment]
All builds are processed offline (hence the --offline and --cache options being used).

**Comment by kspearrin** [comment]
It will always fail then unfortunately.

**Comment by ghisvail** [comment]
Looks like `gulp-google-webfonts` is the culprit. I'd have to patch the code base somehow to get the fonts from within the sandbox instead of online.

**Comment by ghisvail** [comment]
I solved the issue by letting `flatpak` manually injecting the fonts to the right location and bypassing the gulp task. The flatpak version of Bitwarden is close to ready.

![capture d ecran de 2018-08-28 12-13-10](https://user-images.githubusercontent.com/1964655/44717994-ee1a2880-aabe-11e8-8b20-5ec57c00a69a.png)

Thank you for your help.
