### ISSUE TITLE
Bitwarden broken on Wayland

### ISSUE THREAD

**Issue by hevanaa** [bitwarden/desktop#1329]
### Steps To Reproduce

1. Login to Linux Gnome desktop with Wayland (Fedora 35)
2. Updated bitwarden to latest version from flatpak
3. Start bitwarden

### Expected Result

Application starts normally with a visible window

### Actual Result

Application starts with a grey or black window and doesn't respond to clicks or key presses. Window can be dragged around and resized, but is still blank/black. 

### Screenshots or Videos

$ flatpak run com.bitwarden.desktop 
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote --enable-crashpad
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 11:17:39.726: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:17:39.726: Failed to load module "pk-gtk-module"
Gtk-Message: 11:17:39.726: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:17:39.726: Failed to load module "pk-gtk-module"
[2:0212/111739.737399:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2:0212/111739.812428:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0212/111739.812456:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0212/111739.812473:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:51822:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:51283:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:51218:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:51209:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:51188:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:51184:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:51209:79)
    at IpcMainImpl.emit (node:events:394:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:51822:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:51283:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:51218:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:51209:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:51188:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:51184:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:51209:79)
    at IpcMainImpl.emit (node:events:394:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
11:17:50.490 › TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:52204:36)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:52019:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:52015:12)
    at WindowMain.updateWindowState (/app/Bitwarden/resources/app.asar/main.js:52199:16)
    at WindowMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:52153:28)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:52019:71
    at new Promise (<anonymous>)

### Additional Context

- When logging into Gnome with Xorg, application starts normally.
- When applying argument "--no-sandbox" from command line (in wayland session), application starts normally

### Operating System

Linux

### Operating System Version

Fedora 35 (driver proprietary Nvidia 510.47)

### Installation method

Flatpak

### Build Version

1.31.2

**Comment by Hinton** [comment]
Bitwarden does not currently maintain an official flatpack package. https://flathub.org/apps/details/com.bitwarden.desktop seems to point to https://github.com/flathub/com.bitwarden.desktop. For flatpack related issues I would suggest filing an issue towards that repo.

A list of officially maintained distributions can be found on the website, https://bitwarden.com/download/.
