### ISSUE TITLE
Node-gyp issue on debian

### ISSUE THREAD

**Issue by tuv7041** [bitwarden/desktop#161]
I'm trying to manually compile bitwarden's desktop version on debian, and I couldn't find a tutorial on how to do it. The README only shows the npm install && npm run electron commands. When running npm install, it always fails in the node-gyp rebuild part with an access denied (even when running as root or with sudo).

```
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/user/bitwarden/desktop/node_modules/desktop-idle/build'
gyp ERR! System Linux 4.18.0-2-amd64
```

Searching for this error, or even for "node-gyp" on the issues site, not only for the desktop version but every version returns empty results...

Trying with the --unsafe-perm option fails also:

```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:349:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.0-2-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
```

Has anybody managed to compile it correctly or does everybody just use the release version (which you can't really verify...)

**Comment by kspearrin** [comment]
You need to install the dependencies of `desktop-idle`. See https://www.npmjs.com/package/desktop-idle#linux-requirements

**Comment by tuv7041** [comment]
That didn't work. Installed the dependencies and when trying to install either desktop-idle or bitwarden I get the same issue with node-gyp:
```

> desktop-idle@1.1.2 install /home/user/bitwarden/desktop/node_modules/desktop-idle
> node-gyp rebuild

Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Package xext was not found in the pkg-config search path.
Perhaps you should add the directory containing `xext.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xext' found
Package xscrnsaver was not found in the pkg-config search path.
Perhaps you should add the directory containing `xscrnsaver.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xscrnsaver' found
gyp: Call to 'pkg-config --cflags x11 xext xscrnsaver' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.0-2-amd64

```

**Comment by SaeedBaig** [comment]
Just wanted to say I had the same issue as @tuv7041 and I was able to fix it by installing the packages containing xext and xscrnsaver. The following worked for me on Kubuntu 18.04:

```
sudo apt-get update
sudo apt-get install libxext-dev    # contains xext
sudo apt-get install libxss-dev     # contains xsrcnsaver
```

After that, you'll have to clone the repo again (otherwise you'll get some error about Electron not being properly installed the first time), but now `npm install` and `npm run electron` should work.

**Comment by KBeDevel** [comment]
I'm getting a similar error when I execute the `npm i`:

```
Package xscrnsaver was not found in the pkg-config search path.
Perhaps you should add the directory containing `xscrnsaver.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xscrnsaver', required by 'virtual:world', not found
gyp: Call to 'pkg-config --cflags x11 xext xscrnsaver' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

I'm using Fedora 31 Workstation with `node@13.11.0`.
