### ISSUE TITLE
AppImage broken after update

### ISSUE THREAD

**Issue by jarthurgross** [bitwarden/desktop#184]
Today Bitwarden prompted me to update, and after updating the AppImage fails to start due to a JavaScript error. Below is the output I get after running `Bitwarden-1.12.0-x86_64.AppImage` from the terminal:

```
/tmp/.mount_BitwarqQ9AIY/bitwarden: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/.mount_BitwarqQ9AIY/bitwarden)
/tmp/.mount_BitwarqQ9AIY/bitwarden: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/.mount_BitwarqQ9AIY/bitwarden)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.6HPJeY)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_BitwarqQ9AIY/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/tmp/.mount_BitwarqQ9AIY/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
```

It looks like a library problem, which confuses me because I thought the AppImage would take care of most of those problems, but maybe I don't have some core library that the AppImage expects me to have since I'm running an old OS.

My system is running Linux Mint 17 'Qiana', Xfce 64-bit.

**Comment by kspearrin** [comment]
Looks like the errors are coming from keytar, which uses libsecret. https://github.com/atom/node-keytar

Is the libsecret package available on this OS?

**Comment by roadkills-r-us** [comment]
I am seeing the same problem on RHEL 7.5. It happens with the .AppImage and the RPM.
libsecret is installed. Both it an dthe BitWarden binary are x86_64.

**Comment by roadkills-r-us** [comment]
Per someone else here, "Yeah, Redhat 7 tops out at 1.3.7 for CXXABI."

**Comment by tukusejssirs** [comment]
I have same problem on Centos 7 (GNOME 3 Desktop).

Steps to reproduce:

```bash
wget "https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage"
chmod +x Bitwarden-x86_64.AppImage
./Bitwarden-x86_64.AppImage
```
Output of the last command:
```bash
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.Sj1g8J)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_bitwarIKmjkS/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/tmp/.mount_bitwarIKmjkS/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
```

**Comment by kspearrin** [comment]
@tukusejssirs Is libsecret installed?

**Comment by tukusejssirs** [comment]
@kspearrin, yes, I have `libsecret-0.18.6-1.el7.x86_64` installed.

**Comment by slorenzo** [comment]
I got the same error, is there any workaround?

**Comment by tukusejssirs** [comment]
@slorenzo, use other options, like a browser extension. I use one for Firefox.

Still, this issue must be solved.

**Comment by tukusejssirs** [comment]
@slorenzo, I found out that adding `--no-sandbox` option make the `*.appimage` running. However, I did not have enough time yet to search how to make the sandbox configured (the issue is that the sandbox is not configured).

**Comment by labor4** [comment]
for me: 
```
./Bitwarden-1.24.6-x86_64.AppImage --no-sandbox %U
```
**doesn't work anymore**, and was working before the self-update, while **on latest Centos 7.9**
```
$ cat /etc/centos-release 
CentOS Linux release 7.9.2009 (Core)
```
and is producing a similar
```
$ ./Bitwarden-1.24.6-x86_64.AppImage --no-sandbox %U
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.2V5ivr)
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/tmp/.mount_BitwarIQLIHB/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
```

**Comment by labor4** [comment]
BTW
I switched to the **snap version**, since itŝ marked with a encouraging green "verified account" badge.
```
# (centos 7.9 with snapd installed)
sudo snap install bitwarden
```

and this one works.
