### ISSUE TITLE
Bitwarden 1.12.0 AppImage Not executing on RHEL 7 

### ISSUE THREAD

**Issue by prudentcircle** [bitwarden/desktop#223]
I downloaded an AppImage file, ran it on RHEL 7.
I got the following error

```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.ydeLwS)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_BitwaruqTjVH/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/tmp/.mount_BitwaruqTjVH/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
```
I did some research and found that I needed to install libsecret-devel.
I installed it. No luck there.

I am currently running RHEL 7.6 Enterprise Linux
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.6 (Maipo)
```

**Comment by kspearrin** [comment]
I'm not sure. What about another package, like the snap? Does that work?

**Comment by prudentcircle** [comment]
I tried Flatpak instead, and it works great.
I have not tried Snap.

**Comment by SysAlex** [comment]
Bitwarden-1.14.0-x86_64.rpm - is not x86_64 arch software installation.
libstdc++.so.6 - is i686 (x32) library and conflicts with installed x86_64 arch package.

**Comment by djsmith85** [comment]
Hi @prudentcircle, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
