### ISSUE TITLE
“Rebuild Failed” when doing “npm install“ 

### ISSUE THREAD

**Issue by pachulo** [bitwarden/desktop#248]
I'm trying to compile the app, but when I execute `npm install` I get this error:

```
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/1793/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> bitwarden@0.0.0 postinstall /home/pachulo/Software/github/bitwarden-desktop
> electron-rebuild && npm run sub:init && gulp postinstall

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild

Failed with exit code: 7

Error: 
Failed with exit code: 7
    at SafeSubscriber._error (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.error (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:201:26)
    at Subscriber._error (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at Subscriber.error (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at SafeSubscriber._next (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrSetError (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:251:16)
    at SafeSubscriber.next (/home/pachulo/Software/github/bitwarden-desktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:191:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! bitwarden@0.0.0 postinstall: `electron-rebuild && npm run sub:init && gulp postinstall`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the bitwarden@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pachulo/.npm/_logs/2019-04-17T22_30_31_936Z-debug.log

```

I'm using Ubuntu 16.04 and the node snap:

```
2 info using npm@6.4.1
3 info using node@v10.15.3
```

I think that I installed all the dependencies that I know of:
`sudo apt install libx11-dev libxext-dev libxss-dev libsecret-1-dev`

Wha am I missing?

**Comment by pachulo** [comment]
OK, the relevant bit is the first Warning:
```npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/1793/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.```

And it can be solved like this:
> --scripts-prepend-node-path is the key, simply create a file at the root folder of the app, called .npmrc, place this line into it solved the problem:
> 
> scripts-prepend-node-path=true

From https://stackoverflow.com/a/51295237
