### ISSUE TITLE
macbook cant login into desktop app 

### ISSUE THREAD

**Issue by Tealk** [bitwarden/desktop#501]
## Describe the Bug

I can log in on, with the app, not on my self-hosted server.

## Steps To Reproduce

1. enter server in the settings
2. enter mail and password
3. Enter 2fa

## Expected Result

I am logged in and can manage my passwords

## Actual Result

I get the following error
<img width="958" alt="Bildschirmfoto 2020-08-02 um 13 27 36" src="https://user-images.githubusercontent.com/12276250/89122040-6025f400-d4c4-11ea-959d-0e4034f65174.png">

## Environment

- Operating system: [MacOS 10.15.6
- Build Version (go to "Settings" → "About"): 1.20.0
- Server: 1.36.1

## Additional Context

i have no problem logging in to the firefox extension

**Comment by kspearrin** [comment]
Can you check the server logs right after failing to log in using `docker logs bitwarden-identity`

**Comment by Tealk** [comment]
Here the extract of the log, I hope this is sufficient:

```
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
info: IdentityServer4.Validation.TokenRequestValidator[0]
      User authentication failed: Two factor required., details: {
        "ClientId": "desktop",
        "GrantType": "password",
        "Scopes": "api offline_access",
        "UserName": "***USERNAME***",
        "Raw": {
          "scope": "api offline_access",
          "client_id": "desktop",
          "grant_type": "password",
          "username": "***USERNAME***",
          "password": "***REDACTED***",
          "deviceType": "7",
          "deviceIdentifier": "2525f383-0bd0-47a7-890d-87d0bf0ed5f9",
          "deviceName": "macos"
        }
      }
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 355.482ms 400 application/json; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-configuration  
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 4.4738ms 200 application/json; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.0 POST http://***DOMAIN***/connect/token application/x-www-form-urlencoded; charset=utf-8 294
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
fail: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[48]
      An error occurred while reading the key ring.
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1.GenerateAsync(String purpose, UserManager`1 manager, TUser user)
   at Bit.Core.IdentityServer.BaseRequestValidator`1.BuildSuccessResultAsync(User user, T context, Device device, Boolean sendRememberToken) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 150
   at Bit.Core.IdentityServer.BaseRequestValidator`1.ValidateAsync(T context, ValidatedTokenRequest request) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 116
   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/runner/work/server/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 45
   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM1MQ3VSAL6T", Request id "0HM1MQ3VSAL6T:00000001": An unhandled exception was thrown by the application.
System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1.GenerateAsync(String purpose, UserManager`1 manager, TUser user)
   at Bit.Core.IdentityServer.BaseRequestValidator`1.BuildSuccessResultAsync(User user, T context, Device device, Boolean sendRememberToken) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 150
   at Bit.Core.IdentityServer.BaseRequestValidator`1.ValidateAsync(T context, ValidatedTokenRequest request) in /home/runner/work/server/server/src/Core/IdentityServer/BaseRequestValidator.cs:line 116
   at Bit.Core.IdentityServer.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in /home/runner/work/server/server/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:line 45
   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Bit.Core.Utilities.CurrentContextMiddleware.Invoke(HttpContext httpContext, CurrentContext currentContext, GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CurrentContextMiddleware.cs:line 19
   at Bit.Core.Utilities.ServiceCollectionExtensions.<>c__DisplayClass10_0.<<UseDefaultMiddleware>b__1>d.MoveNext() in /home/runner/work/server/server/src/Core/Utilities/ServiceCollectionExtensions.cs:line 448
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 308.9051ms 500 
```

**Comment by cscharf** [comment]
Please see: https://github.com/dotnet/aspnetcore/issues/12830 as this details the root issue and resolution. The referenced issue is a Windows host, but the same issue would hold true due the same underlying framework on linux host, please see directory `$HOME/.aspnet/DataProtection-Keys` for any empty XML files and delete those files, then restart the server/service.

**Comment by Tealk** [comment]
> please see directory $HOME/.aspnet/DataProtection-Keys for any empty XML files and delete those files, then restart the server/service.

where do i find this file? i guess in a docker container? if so, which one?

**Comment by cscharf** [comment]
That would be in the `bitwarden/identity` container.

**Comment by Tealk** [comment]
how exactly do I do that?

**Comment by cscharf** [comment]
So, you can run remote commands/shell in your container, e.g., Use `docker ps` to get the name of the container, looking for the one running from the image, `bitwarden/identity`. Then use the command `docker exec -it <container name> /bin/bash` to get a bash shell in the container OR, you can generically use `docker exec -it <container name> <command> to run commands in your container as well. With that, using something like the following could work:
```
<local prompt>:~ <username>$ docker exec -it <container name> /bin/bash
[root@<container name>:/# ls -sh $HOME/.aspnet/DataProtection-Keys | grep "0 k"
```

**Comment by Tealk** [comment]
unfortunately this does not seem to be the correct directory
ls: cannot access '/root/.aspnet/DataProtection-Keys': No such file or directory

**Comment by thekazian** [comment]
Try looking for and deleting the .xml files in the location `/etc/bitwarden/core/aspnet-dataprotection` within the container. Then remember to restart the server/service.

**Comment by Tealk** [comment]
> Try looking for and deleting the .xml files in the location `/etc/bitwarden/core/aspnet-dataprotection` within the container. Then remember to restart the server/service.

all of them or only the one with 0k?

**Comment by cscharf** [comment]
Just the one with `0k`, it's the empty one that's causing the exception.

**Comment by Tealk** [comment]
Thanks for your help, now it works again.
