### ISSUE TITLE
App not starting on Fedora 34 with wayland and gnome 40

### ISSUE THREAD

**Issue by WAPEETY** [bitwarden/desktop#956]
## Describe the Bug

I can´t start the app on my laptop, when I start it just display a white window until gnome says "Bitwarden is not responding"

## Steps To Reproduce

1. Install fedora 34 with wayland and gnome 40
2. Install Bitwarden from Flatpak (FlatHub)

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/38016769/122110417-cb4b9100-ce1e-11eb-8720-ba2d5679c2c2.png)

## Environment

- Operating system: GNU/Linux - Fedora 34 with Gnome 40 on wayland
- Installation method: Downloaded from Flatpak (FlatHub) 
- Build Version: 1.26.5 (saw from gnome software since the program doesn't start)
## StackTrace

EDIT: Actually this stacktrace has apparently nothing to do with the problem, on the same computer using X server instead of wayland the application works fine

```[wapeety@thinkpad bin]$ ./com.bitwarden.desktop
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
Gtk-Message: 21:33:48.099: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:33:48.099: Failed to load module "pk-gtk-module"
Gtk-Message: 21:33:48.099: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:33:48.100: Failed to load module "pk-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
(node:2) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setContextMenu' of undefined
    at tray_main_TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:19568:23)
    at messaging_main_MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:19052:28)
    at messaging_main_MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:18993:22)
    at messaging_main_MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:18984:154)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:18962:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:18958:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:18984:82)
    at IpcMainImpl.emit (events.js:315:20)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by eliykat** [comment]
Thanks for the report! It looks like this has already been reported in #934, so I'll close this thread as a duplicate. (Thanks @eihli for the heads up)

**Comment by WAPEETY** [comment]
On X11 the app seems to work fine so the issues are unrelated

**Comment by eliykat** [comment]
No worries. It looks like that console error is a common one and has caused us to conflate a few separate issues. I guess the real issue here is Wayland support.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Flathub is community maintained, so here may not be the best place to report regressions for it.

**Comment by WAPEETY** [comment]
> The Flatpak is community maintained, so here may not be the best place to report regression of it.

Sorry didn't know, anyway I'll try to build the app directly from this repo, just to see if it works in that case this issue will be closed

**Comment by eliykat** [comment]
Do you have a secrets/keychain manager app running? See #962. You could try this to see if it resolves the issue: 

> Running gnome-keyring-daemon --start --components=secret results in the application not freezing.

**Comment by WAPEETY** [comment]
> Do you have a secrets/keychain manager app running? See #962. You could try this to see if it resolves the issue:
> 
> > Running gnome-keyring-daemon --start --components=secret results in the application not freezing.
> 
> Otherwise, running from source is a good idea.

So this should fix? I'll try soon

**Comment by septatrix** [comment]
With the current flatpak version this seems to be fixed. Still there are some issues when using the open-source nvidia drivers under wayland though that is not under the control of bitwarden but rather something which has to be fixed in chromium/nouveau etc (https://github.com/flathub/com.bitwarden.desktop/issues/82).

Nevertheless the flatpak ist currently still only community maintained and bugs with it should be reported in their repository. Managing the flatpak however seems to be on the teams roadmap https://github.com/bitwarden/desktop/issues/188#issuecomment-936327927.

**Comment by BierDav** [comment]
When launching via terminal I encountered multiple problems. First was a wrong .desktop file in var/lib/snapd/desktop/applications/. It should be bitwarden_Bitwarden.desktop, but it was bitwarden_bitwarden.desktop. Notice the uppercase letter in the second bitwarden name.

After renaming the file i had to agree to permissions and got following error:

![image](https://user-images.githubusercontent.com/46626041/160291812-587b1868-0d85-451a-9125-23345b9206f8.png)

**Comment by Ezwen** [comment]
Same problem here with Fedora 36, GNOME, and Nvidia proprietary drivers running on Wayland.

**Comment by KoreWaMessatsu** [comment]
> Same problem here with Fedora 36, GNOME, and Nvidia proprietary drivers running on Wayland.

Yeah, same problem here.
