### ISSUE TITLE
Freeze on launch until after a `setContextMenu` exception.

### ISSUE THREAD

**Issue by eihli** [bitwarden/desktop#962]
I just built a fresh AppImage using (`commit 392d7b7638c86c4c757e49ba4580dbfc4e92fcca (HEAD -> rc, origin/rc)`) and I'm getting this exception.

```
➜  desktop git:(rc) dist/Bitwarden-1.26.5-x86_64.AppImage                                  
(node:47690) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:47690) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
17:27:23.731 › Checking for update
17:27:24.412 › Update for version 1.26.5 is not available (latest version: 1.26.5, downgrade is disallowed).
(node:47690) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setContextMenu' of undefined
    at tray_main_TrayMain.updateContextMenu (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:2060:23)
    at messaging_main_MessagingMain.updateTrayMenu (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1509:28)
    at messaging_main_MessagingMain.onMessage (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1450:22)
    at messaging_main_MessagingMain.<anonymous> (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1441:154)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1419:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1415:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1441:82)
    at IpcMainImpl.emit (events.js:315:20)
(node:47690) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47690) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The app launches and I can interact with the menu but nothing inside the window is responsive. I can see the fields for username and password but there is no blinking cursor in them and I can't interact with them. It sits this way for about 30 seconds until I get that exception and then I'm finally able to interact with elements in the window. I haven't tried logging in and using the app further than that.

Arch Linux, StumpWM

---

### Update 1

I'm going to take some notes here in hopes it helps resolve this.

In the tray's initialization, we conditionally call `showTray`. 

`showTray` is what creates the `Tray` object and assigns it to `this.tray`.

What happens if the user doesn't have a system tray? If `showTray` never gets called, then `this.tray` never gets initialized, but `updateAppMenu` still gets called which kicks of the chain where eventually `updateContextMenu` gets called.

```
    // TrayMain
    // ...
    async init(appName: string, additionalMenuItems: MenuItemConstructorOptions[] = null) {
       // ...
        this.contextMenu = Menu.buildFromTemplate(menuItemOptions);
        if (await this.storageService.get<boolean>(ElectronConstants.enableTrayKey)) {
            this.showTray();
        }
    }
```

```
    showTray() {
        if (this.tray != null) {
            return;
        }

        this.tray = new Tray(this.icon);
        this.tray.setToolTip(this.appName);
        // ...
        if (this.contextMenu != null && !this.isDarwin()) {
            this.tray.setContextMenu(this.contextMenu);
        }
    }
```

`updateContextMenu` expects `this.tray` to be defined (expects `showTray` to have ran successfully).

```
    updateContextMenu() {
        if (this.contextMenu != null && this.isLinux()) {
            this.tray.setContextMenu(this.contextMenu);
        }
    }
```

`updateContextMenu` gets called by `updateTrayMenu` which gets called by the messaging service.

```
    // MessagingMain
    // ...
    init() {
        // ...
        ipcMain.on('messagingService', async (event: any, message: any) => this.onMessage(message));
    }

    onMessage(message: any) {
        switch (message.command) {
            case 'scheduleNextSync':
                this.scheduleNextSync();
                break;
            case 'updateAppMenu':
                this.main.menuMain.updateApplicationMenuState(message.isAuthenticated, message.isLocked);
                this.updateTrayMenu(message.isAuthenticated, message.isLocked);
                break;
```

---

### Update 2

I'm trying to track this down. 

Here's the result of a few console.logs I threw around. This includes a `console.log` in `showTray`, which you'll notice is never called.

```
➜  desktop git:(rc) ✗ ELECTRON_IS_DEV=1 ./dist/Bitwarden-1.26.5-x86_64.AppImage
2021-06-17T13:16:29.425Z  messagingMain initialized from main.ts
2021-06-17T13:16:29.965Z trayMain about to init from main.ts
2021-06-17T13:16:29.966Z tray.main.ts init pre-await
2021-06-17T13:16:29.966Z tray.main.ts init post-await
2021-06-17T13:16:29.966Z awaiting storageService from main.ts#bootstrap
2021-06-17T13:16:30.034Z bootstrap complete
(node:71706) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
2021-06-17T13:16:30.970Z received message { command: 'syncStarted' }
2021-06-17T13:16:31.013Z received message { command: 'syncCompleted', successfully: false }
2021-06-17T13:16:31.068Z received message { command: 'authBlocked' }
// **** ~35 second delay... app frozen.
2021-06-17T13:18:57.094Z received message { command: 'updateAppMenu', isAuthenticated: false, isLocked: true }
2021-06-17T13:18:57.096Z updateAppMenu message
updateTrayMenu
Thu Jun 17 2021 08:18:57 GMT-0500 (Central Daylight Time) updateContextMenu
(node:71706) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setContextMenu' of undefined
```

The delay varies between ~20 seconds and ~40 seconds, so maybe something IO-bound rather than a hard-coded timeout?

Still narrowing in on what happens between bootstrapping and the first `updateAppMenu` message.

Actually... here's something kind of odd.

In `TrayMain` I'm logging `"tray.main.ts init post-await"` *immediately* befor calling `this.showTray();`. And in `showTray()` I'm *immediately* logging again. I see the `tray.main.ts init post-await` message but I don't see the `showTray` message.

```
    async init(appName: string, additionalMenuItems: MenuItemConstructorOptions[] = null) {
        // ...
        this.contextMenu = Menu.buildFromTemplate(menuItemOptions);
        console.log(new Date(), "tray.main.ts init pre-await");
        if (await this.storageService.get<boolean>(ElectronConstants.enableTrayKey)) {
            console.log("tray.main.ts init post-await");
            this.showTray();
        }
        console.log(new Date(), "tray.main.ts init post-await");
    }
```

```
    showTray() {
        console.log("showTray");
        if (this.tray != null) {
            return;
        }
        // ...
    }
```

**Comment by eihli** [comment]
Anyone have any idea on how to pause on breakpoints?

I found the `--inspect` and `chrome://inspect` to connect to the remote debugging port of the main process, but I'm not able to get it to pause on the break points.

I'm currently trying launching with

```
    "electron": "npm run build:main:dev && concurrently -k -n Main,Rend -c yellow,cyan \"electron --inspect --inspect-brk:5858 ./build --watch\" \"npm run build:renderer:watch\"",
```

and then connecting as soon as it shows up at `chrome://inspect/#devices`,

```
            this.contextMenu = Menu.buildFromTemplate(menuItemOptions);
            debugger;
            console.log(new Date(), "tray.main.ts init pre-await");
```

but I can't get it to pause on any breakpoints.

**Comment by eliykat** [comment]
Nice work finding the culprit here. I haven't reproduced it yet, but I assume that's why I couldn't repro it on Ubuntu - I would've had `gnome-keyring-daemon` running on system startup.

I've asked the team for some tips on debugging the main process - so far I've managed to avoid it myself.

Browser doesn't suffer from this issue because it doesn't use the system keychain (I assume due to API limitations of the browser environment). That's why you need the desktop app running to use biometrics in the browser extension.

I'll consider what we can do about this in terms of a fix.

**Comment by MGibson1** [comment]
@eihli I just recently merged a PR that includes source maps for the main process in development builds (https://github.com/bitwarden/desktop/pull/946).

As long as you're up to date with master, what you're trying should work. However, I haven't tested using chrome's debugger, I use vs code's, which automatically attaches when you run `npm run electron` in the vs code terminal.

Prior to that PR, you could still debug main process, but you had to do it from the transpiled `js` code

**Comment by eliykat** [comment]
@eihli Unfortunately all of keytar's methods appear to be blocking - even though they're wrapped in promises so they _look_ asynchronous. I can't see any safe method available for us to even check whether there's a secrets service running without hitting the same issue. I don't think there's anything we could do at our level - we'd have to fork or change the keytar dependency.

That may happen at some point in the future, but for now just running the lightest secrets service you can find is the most practical workaround.

**Comment by shroff** [comment]
Facing the same issue here.

I run `gnome-keyring-daemon --start` in my session startup script, but I am still seeing this issue. I know for a fact that the keyring daemon is running because I use it as my ssh agent.

Running Arch/sway.
